# MeetingMind - Prometheus Monitoring Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules and alerting
rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MeetingMind application
  - job_name: 'meetingmind'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['meetingmind:8000']
    scrape_timeout: 5s

  # Nginx monitoring
  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'

  # PostgreSQL monitoring (if using postgres_exporter)
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis monitoring (if using redis_exporter)
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node/System metrics (if using node_exporter)
  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom MeetingMind metrics
  - job_name: 'meetingmind-custom'
    scrape_interval: 5s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['meetingmind:8000']
    params:
      format: ['prometheus']